### ISSUE TITLE
Error in tetrahedralization

### ISSUE THREAD

**Issue by JulienKh** [Concrete-Chrono-Development/chrono-preprocessor#5]
I installed FreeCAD and pulled the Chrono workbench. However, I encountered an error while performing the tetrahedralization. I would like to check if anyone has any ideas why?

**To Note that I am using Ubuntu 22.04.2 LTS as OS**.

The error:

> 13:17:30 Traceback (most recent call last):
> 13:17:30 File "/home/julien/snap/freecad/common/Mod/chrono-preprocessor/freecad/chronoWorkbench/modules/mod_LDPMCSL.py", line 155, in generationDriver
> 13:17:30 driver_LDPMCSL(self,fastGen)
> 13:17:30 File "/home/julien/snap/freecad/common/Mod/chrono-preprocessor/freecad/chronoWorkbench/generation/driver_LDPMCSL.py", line 808, in driver_LDPMCSL
> 13:17:30 tetGen = gen_LDPMCSL_tetrahedralization(internalNodes,surfaceNodes,\
> 13:17:30 File "/home/julien/snap/freecad/common/Mod/chrono-preprocessor/freecad/chronoWorkbench/generation/gen_LDPMCSL_tetrahedralization.py", line 115, in gen_LDPMCSL_tetrahedralization
> 13:17:30 os.rename(Path(tempPath + geoName + '2D.1.ele'),Path(tempPath + geoName \
> 13:17:30 FileNotFoundError: [Errno 2] No such file or directory: '/tmp/chronoConc55234268/LDPMgeo0002D.1.ele' -> '/tmp/chronoConc55234268/LDPMgeo000.ele'

![Screenshot from 2024-02-15 13-26-21](https://github.com/Concrete-Chrono-Development/chrono-preprocessor/assets/148353873/c6ed67ad-e4fa-4642-be58-120e0cb07128)

**Comment by JulienKh** [comment]
The above issue has been resolved through the recompilation of tetgen.
However, i encountered a new error while writing visualization files.

Error:

> 
> 10:45:00  Traceback (most recent call last):
> 10:45:00    File "/home/julien/snap/freecad/common/Mod/chrono-preprocessor/freecad/chronoWorkbench/modules/mod_LDPMCSL.py", line 155, in generationDriver
> 10:45:00      driver_LDPMCSL(self,fastGen)
> 10:45:00    File "/home/julien/snap/freecad/common/Mod/chrono-preprocessor/freecad/chronoWorkbench/generation/driver_LDPMCSL.py", line 1074, in driver_LDPMCSL
> 10:45:00      os.rename(Path(tempPath),Path(outDir + outName))
> 10:45:00  OSError: [Errno 18] Invalid cross-device link: '/tmp/chronoConc34284796' -> '/home/julien/snap/freecad/common/chronoWorkbench/LDPMgeo000Box000'

![Screenshot from 2024-02-19 10-45-52](https://github.com/Concrete-Chrono-Development/chrono-preprocessor/assets/148353873/73285326-627f-48d5-b0ea-a87f9a5bfbd0)
